language: python
python:
  - "3.5"
  - "3.6"
jobs:
  include:
  - python: 3.6
    env: TOXENV=lint
install:
  - pip install tox-travis codecov
script:
  - tox
  - codecov
before_install:
  - sudo apt-get -qq install software-properties-common
  - sudo add-apt-repository -y ppa:neovim-ppa/unstable
  - sudo apt-get -qq update
  - sudo apt-get install -y neovim
