language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "3.8-dev"
jobs:
  include:
  - python: 3.7
    env: TOXENV=lint
before_install:
  - wget -O nvim https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
  - chmod +x nvim
  - export PATH="$PATH:."
install:
  - pip3 install tox-travis codecov
script:
  - nvim --version
  - tox
  - codecov
